[package]
name = "part_10"
version = "0.10.0"
authors = ["Crocodile Space Pope"]

[dependencies]
tcod = { version = "0.12", features = ["serialization"] }
rand = "0.5"
textwrap = "0.10.0"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"